services:
  #Database
  database:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - taskManager-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #PGAdmin
  pgadmin:
    image: dpage/pgadmin4:9.15
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - taskManager-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database

  #UI
  UI:
    image: ghcr.io/devtiro/devtiro-build-task-app:latest
    restart: unless-stopped
    environment:
      BACKEND_HOST: host.docker.internal
      BACKEND_PORT: "8080"
    ports:
      - "3000:3000"
    networks:
      - taskManager-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  taskManager-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: